name: paperclip_app
description: Paperclip Anti-Cheating App

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  lottie: ^2.3.2  # Added Lottie package
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.10.2
  webview_flutter_wkwebview: ^3.10.2
  http: ^1.1.0 # Add this line
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  permission_handler: ^12.0.0
  package_info_plus: ^8.0.0 # Add this line
  url_launcher: ^6.3.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-square-purp.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/  # Folder for images
    - assets/animations/  # Folder for Lottie animations
    
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
          