name: paperclip_app
description: Paperclip Anti-Cheating App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  lottie: ^2.3.2  # Added Lottie package
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.10.2
  webview_flutter_wkwebview: ^3.10.2
  http: ^1.1.0 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/  # Folder for images
    - assets/animations/  # Folder for Lottie animations
    
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
          